---
- name: Configure Production Environment
  hosts: localhost
  become: yes

  tasks:
    - name: Update Package Cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Create Directories
      file:
        path: "/opt/myapp"
        state: directory
        owner: john
        group: john
        mode: 0755
      become: yes

    - name: Copy Configuration File
      copy:
        src: files/app-config.yml
        dest: "/opt/myapp/app-config.yml"
        owner: john
        group: john
        mode: 0644
      become: yes

    - name: Ensure 'wheel' Group Exists
      group:
        name: wheel
        state: present
      become: yes

    - name: Configure Users
      user:
        name: john
        state: present
        groups: wheel
      become: yes

    - name: Restart Application Service
      systemd:
        name: myapp.service
        state: restarted
      become: yes
      when: ansible_os_family == 'Debian'
