name: 'Install Python Dependencies'

description: 'Install Python dependencies using PIP'

inputs:
  requirements-file:
    description: 'Path to the requirements file'
    required: true
    default: 'requirements.txt'

runs:
  using: 'docker'
  image: 'python:3.12' 

steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up Python
    run: |
      python -m pip install --upgrade pip

  - name: Install dependencies
    run: |
      python -m pip install -r ${{ inputs.requirements-file }}
      pip install black
      pip install bandit
      pip install mypy
