name: Code Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test_app.py

    - name: Check code style
      run: |
        flake8

    - name: Check code formatting
      run: |
        black --check .

    - name: Check for security vulnerabilities
      run: |
        bandit -r .

    - name: Run type checking
      run: |
        mypy --strict .

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to production
      # Add deployment steps here (e.g., deploy to a server)
      run: echo "Deploying to production..."
